import { z } from "zod";
export const dataStockUpdateScheme = z.object({
    // part_name: z.string(),
    // name_casting: z.string(),
    before_casting: z.string(),
    in_casting: z.string(),
    // name_machining: z.string(),
    before_machining: z.string(),
    in_machining: z.string(),
    after_machining: z.string(),
    // name_painting: z.string(),
    before_paiting: z.string(),
    in_painting: z.string(),
    after_painting: z.string(),
    // name_sc_painting: z.string(),
    before_sc_painting: z.string(),
    in_sc_painting: z.string(),
    after_sc_painting: z.string(),
    // name_sc_finishing: z.string(),
    before_sc_finishing: z.string(),
    in_sc_finishing: z.string(),
    after_sc_finishing: z.string(),
    // name_finished_good: z.string(),
    before_finished_good: z.string(),
    in_finished_good: z.string(),
    after_finished_good: z.string(),
});
